% Entropy Analysis Script for Multimodal Physiological Signals (MATLAB Version)
% This script analyzes Gaze and EEG entropy using CSV data generated by the
% Python analysis pipeline.
% 
% Usage:
%   Run this script in MATLAB. Ensure the CSV files exist in:
%   7_Analysis/raw_result/entropy_analysis/
% 
% Author: CNElab (Converted from Python)
% Date: 2026

% =========================================================================
% Setup
% =========================================================================
clear; clc; close all;

% Determine paths
scriptPath = fileparts(mfilename('fullpath'));
projectRoot = fullfile(scriptPath, '..', '..');
dataDir = fullfile(projectRoot, '7_Analysis', 'raw_result', 'entropy_analysis');
outputFigDir = fullfile(projectRoot, '7_Analysis', 'figures', 'entropy_analysis_matlab');

% Create output directory if it doesn't exist
if ~exist(outputFigDir, 'dir')
    mkdir(outputFigDir);
end

fprintf('=================================================================\n');
fprintf('Entropy Analysis Pipeline (MATLAB)\n');
fprintf('Data Directory: %s\n', dataDir);
fprintf('Output Directory: %s\n', outputFigDir);
fprintf('=================================================================\n\n');

% Standard 32 Channels
channelNames = {'Fp1', 'Fp2', 'F7', 'F3', 'Fz', 'F4', 'F8', ...
                'FT9', 'FC5', 'FC1', 'FC2', 'FC6', 'FT10', ...
                'T7', 'C3', 'Cz', 'C4', 'T8', ...
                'TP9', 'CP5', 'CP1', 'CP2', 'CP6', 'TP10', ...
                'P7', 'P3', 'Pz', 'P4', 'P8', ...
                'O1', 'Oz', 'O2'};

% Define conditions for consistent ordering/coloring
conditions = {'Single', 'Competition', 'Cooperation'};
colors = [0.55, 0.63, 0.80;   % Single
          0.99, 0.55, 0.38;   % Competition
          0.40, 0.76, 0.65];  % Cooperation

% Custom Model Colors (9 distinct colors for ROC and Loss comparison)
model_colors = [
    0.55, 0.63, 0.80;  % 1. Grey Blue Purple
    0.85, 0.60, 0.75;  % 2. Orchid Pink
    0.40, 0.76, 0.65;  % 3. Lake Green
    0.90, 0.40, 0.45;  % 4. Soft Red
    0.60, 0.50, 0.70;  % 5. Grape Purple
    0.95, 0.80, 0.40;  % 6. Mustard Yellow
    0.99, 0.55, 0.38;  % 7. Salmon Orange
    0.65, 0.65, 0.65;  % 8. Medium Gray
    0.50, 0.70, 0.30]; % 9. Olive Green

% --- Global Model Discovery (for consistent ordering across all plots) ---
% Find all directories starting with 'early_' or 'late_'
rawResultDir = fullfile(projectRoot, '7_Analysis', 'raw_result');
allItems = dir(rawResultDir);
modelDirs = {};

for i = 1:length(allItems)
    if allItems(i).isdir && ...
       (startsWith(allItems(i).name, 'early_') || startsWith(allItems(i).name, 'late_'))
        modelDirs{end+1} = allItems(i).name;
    end
end
% Sort alphabetically to ensure Model 1 is always Model 1
modelDirs = sort(modelDirs);
fprintf('Found %d model directories (Sorted alphabetically).\n', length(modelDirs));


% =========================================================================
% Part 1: Gaze Entropy Analysis
% =========================================================================
gazeFile = fullfile(dataDir, 'gaze_entropy_raw.csv');
hasGaze = false;

if exist(gazeFile, 'file')
    fprintf('Loading Gaze data: %s\n', gazeFile);
    gazeData = readtable(gazeFile);
    
    % Convert condition to categorical for easier plotting
    gazeData.condition = categorical(gazeData.condition, conditions);
    
    hasGaze = true;
    
    % --- 1.1 Summary Statistics ---
    fprintf('Computing Gaze Summary Statistics...\n');
    gazeStats = grpstats(gazeData, 'condition', {'mean', 'std', 'min', 'max'}, 'DataVars', 'spatial_entropy');
    disp(gazeStats);
    
    % Save summary
    writetable(gazeStats, fullfile(dataDir, 'matlab_gaze_summary.csv'));
    
    % --- 1.2 Visualization: Raincloud Plot (Gaze) ---
    fprintf('Generating Gaze Raincloud Plot (Horizontal)');
    figure('Name', 'Gaze Entropy Raincloud', 'Color', 'w', 'Position', [100, 100, 800, 600]);
    
    % Add raincloudplots to path
    addpath(genpath(fullfile(scriptPath, 'raincloudplots')));
    
    % Prepare data (3x1 Cell Array)
    data_gaze = cell(3, 1);
    data_gaze{1, 1} = gazeData.spatial_entropy(gazeData.condition == 'Single');
    data_gaze{2, 1} = gazeData.spatial_entropy(gazeData.condition == 'Competition');
    data_gaze{3, 1} = gazeData.spatial_entropy(gazeData.condition == 'Cooperation');
    
    % Plot Horizontal (param=1)
    h_gaze = rm_raincloud(data_gaze, [0.5 0.5 0.5], 1, 'ks');
    
    % Apply distinct colors manually
    for i = 1:3
        h_gaze.p{i, 1}.FaceColor = colors(i, :);
        h_gaze.p{i, 1}.FaceVertexCData = colors(i, :);
        h_gaze.s{i, 1}.MarkerFaceColor = colors(i, :);
        h_gaze.s{i, 1}.MarkerEdgeColor = 'none';
        h_gaze.m(i, 1).MarkerFaceColor = colors(i, :);
    end
    
    title('Gaze Spatial Entropy Distribution');
    xlabel('Spatial Entropy (bits)');
    ylabel('Condition');
    set(gca, 'YTick', 1:3);
    set(gca, 'YTickLabel', {'Single', 'Competition', 'Cooperation'});
    grid on;
    saveas(gcf, fullfile(outputFigDir, 'fig_gaze_raincloud.png'));
    
    % --- 1.3 Visualization: Gaze Entropy by Pair ID (Sorted by Mean, Horizontal) ---
    figure('Name', 'Gaze Entropy by Pair ID', 'Color', 'w', 'Position', [100, 100, 800, 1000]);
    
    % Calculate sorting key
    pairCondStats = grpstats(gazeData, {'pair_id', 'condition'}, 'mean', 'DataVars', 'spatial_entropy');
    pairStats = grpstats(pairCondStats, 'pair_id', 'mean', 'DataVars', 'mean_spatial_entropy');
    pairStats = sortrows(pairStats, 'mean_mean_spatial_entropy', 'ascend');
    
    sortedPairs = pairStats.pair_id;
    overallMeans = pairStats.mean_mean_spatial_entropy;
    
    gazeData.pair_id = categorical(gazeData.pair_id);
    gazeData.pair_id = reordercats(gazeData.pair_id, string(sortedPairs));
    
    boxchart(gazeData.pair_id, gazeData.spatial_entropy, ...
        'GroupByColor', gazeData.condition, ...
        'Orientation', 'horizontal');
    hold on;
    
    plot(overallMeans, 1:length(sortedPairs), '-dk', ...
        'LineWidth', 1.5, ...
        'MarkerFaceColor', 'w', 'MarkerSize', 6, ...
        'DisplayName', 'Mean (Avg of Conditions)');
    
    title('Gaze Spatial Entropy Distribution by Pair ID (Sorted)');
    ylabel('Pair ID');
    xlabel('Spatial Entropy (bits)');
    legend('Location', 'northeastoutside');
    grid on;
    colororder(colors);
    hold off;
    saveas(gcf, fullfile(outputFigDir, 'fig_gaze_entropy_by_pair_sorted_horizontal.png'));
    
    % --- 1.4 ROC Curves Analysis (Comparison) ---
    fprintf('Generating Combined ROC Curve Comparison (Macro Avg)');
    
    if ~isempty(modelDirs)
        figROC = figure('Name', 'ROC Comparison All Models', 'Color', 'w', 'Position', [100, 100, 900, 800]);
        hold on;
        
        for i = 1:length(modelDirs)
            modelName = modelDirs{i};
            rocFile = fullfile(rawResultDir, modelName, 'roc_data.csv');
            if exist(rocFile, 'file')
                try
                    rocData = readtable(rocFile);
                    rows = strcmp(rocData.class, 'macro');
                    if any(rows)
                        fpr = rocData.fpr(rows);
                        tpr = rocData.tpr(rows);
                        aucVal = rocData.auc(find(rows, 1));
                        
                        if startsWith(modelName, 'early', 'IgnoreCase', true), lineStyle = '-';
                        elseif startsWith(modelName, 'late', 'IgnoreCase', true), lineStyle = '--';
                        else, lineStyle = '-.'; end
                        
                        colorIdx = mod(i-1, size(model_colors, 1)) + 1;
                        thisColor = model_colors(colorIdx, :);
                        displayName = strrep(modelName, '_', ' ');
                        
                        plot(fpr, tpr, 'LineStyle', lineStyle, 'Color', thisColor, 'LineWidth', 2.5, ...
                            'DisplayName', sprintf('%s (AUC = %.3f)', displayName, aucVal));
                    end
                catch, end
            end
        end
        plot([0 1], [0 1], ':k', 'HandleVisibility', 'off', 'LineWidth', 1.5);
        xlabel('False Positive Rate');
        ylabel('True Positive Rate');
        title('ROC Curves Comparison (Macro Average)', 'FontSize', 14, 'FontWeight', 'bold');
        legend('Location', 'southeast', 'Interpreter', 'none', 'FontSize', 10);
        grid on; box on; xlim([0 1]); ylim([0 1.02]);
        saveas(figROC, fullfile(outputFigDir, 'fig_roc_comparison_all.png'));
    end
    
    % --- 1.5 Training Loss Comparison ---
    fprintf('Generating Training Loss Comparison...\n');
    lossFile = fullfile(projectRoot, '7_Analysis', 'tables', 'table_gaze_training_loss.csv');
    
    if exist(lossFile, 'file')
        % Preserve headers
        lossData = readtable(lossFile, 'VariableNamingRule', 'preserve');
        
        figLoss = figure('Name', 'Training Loss Comparison', 'Color', 'w', 'Position', [100, 100, 900, 600]);
        hold on;
        
        colNames = lossData.Properties.VariableNames;
        
        % Identify Loss Columns (ending in 'train/loss', ignoring MIN/MAX)
        % We assume these appear in the CSV in the SAME order as 'modelDirs' (sorted)
        lossCols = {};
        for c = 1:length(colNames)
            header = colNames{c};
            if contains(header, 'train/loss') && ~contains(header, 'MIN') && ~contains(header, 'MAX')
                lossCols{end+1} = header;
            end
        end
        
        if length(lossCols) ~= length(modelDirs)
            fprintf('Warning: Number of loss columns (%d) does not match number of models (%d).\n', length(lossCols), length(modelDirs));
            fprintf('Plotting available columns sequentially mapping to sorted models.\n');
        end
        
        nToPlot = min(length(lossCols), length(modelDirs));
        
        for i = 1:nToPlot
            colName = lossCols{i};
            modelName = modelDirs{i}; % Assumed to match
            
            yData = lossData.(colName);
            xData = lossData.Step;
            
            % Determine Style
            if startsWith(modelName, 'early', 'IgnoreCase', true), lineStyle = '-';
            elseif startsWith(modelName, 'late', 'IgnoreCase', true), lineStyle = '--';
            else, lineStyle = '-.'; end
            
            % Determine Color
            colorIdx = mod(i-1, size(model_colors, 1)) + 1;
            thisColor = model_colors(colorIdx, :);
            
            displayName = strrep(modelName, '_', ' ');
            
            plot(xData, yData, 'LineStyle', lineStyle, 'Color', thisColor, 'LineWidth', 2, ...
                'DisplayName', displayName);
        end
        
        xlabel('Epoch (Step)');
        ylabel('Training Loss');
        title('Training Loss Comparison');
        legend('Location', 'northeast', 'Interpreter', 'none');
        grid on; box on;
        
        saveas(figLoss, fullfile(outputFigDir, 'fig_training_loss.png'));
        fprintf('Saved Training Loss figure.\n');
    else
        fprintf('Warning: Training loss file not found at %s\n', lossFile);
    end
    
    % --- 1.6 Confusion Matrix (Early_concat) ---
    fprintf('Generating Confusion Matrix (Early_concat).');
    confMatFile = fullfile(rawResultDir, 'early_(concat)', 'conf_mat.csv');
    if exist(confMatFile, 'file')
        cmTable = readtable(confMatFile, 'ReadRowNames', true);
        figCM = figure('Name', 'Confusion Matrix Early Concat', 'Color', 'w', 'Position', [100, 100, 600, 500]);
        h = heatmap(cmTable.Properties.VariableNames, cmTable.Properties.RowNames, cmTable{:,:});
        h.Title = 'Confusion Matrix: Early (Concat)';
        h.XLabel = 'Predicted'; h.YLabel = 'True';
        baseColor = [0.85, 0.60, 0.75]; % Orchid Pink
        nSteps = 256; r = linspace(1, baseColor(1), nSteps)'; g = linspace(1, baseColor(2), nSteps)'; b = linspace(1, baseColor(3), nSteps)';
        h.Colormap = [r, g, b];
        saveas(figCM, fullfile(outputFigDir, 'fig_conf_mat_early_concat.png'));
    end
    
    % --- 1.7 t-SNE Visualization (Early_concat) ---
    fprintf('Generating t-SNE Visualization (Early_concat)');
    tsneFile = fullfile(rawResultDir, 'early_(concat)', 'tsne_coords.csv');
    if exist(tsneFile, 'file')
        tsneData = readtable(tsneFile);
        figTSNE = figure('Name', 't-SNE Early Concat', 'Color', 'w', 'Position', [100, 100, 700, 600]);
        hold on;
        for i=1:3
            idx = tsneData.label == (i-1);
            scatter(tsneData.tsne_1(idx), tsneData.tsne_2(idx), 30, 'MarkerFaceColor', colors(i,:), ...
                'MarkerEdgeColor', 'none', 'MarkerFaceAlpha', 0.6, 'DisplayName', conditions{i});
        end
        title('t-SNE Visualization: Early (Concat)'); xlabel('Dim 1'); ylabel('Dim 2');
        legend('Location', 'best'); grid on; box on; axis equal;
        saveas(figTSNE, fullfile(outputFigDir, 'fig_tsne_early_concat.png'));
    end
    
    % --- 1.8 Feature PCA Raincloud Plot (Early_concat) ---
    fprintf('Generating Feature PCA Raincloud Plot (Early_concat).');
    featuresFile = fullfile(rawResultDir, 'early_(concat)', 'features.csv');
    tsneFile = fullfile(rawResultDir, 'early_(concat)', 'tsne_coords.csv');
    if exist(featuresFile, 'file') && exist(tsneFile, 'file')
        featTable = readtable(featuresFile); tsneData = readtable(tsneFile);
        if height(featTable) == height(tsneData)
            featData = featTable{:, startsWith(featTable.Properties.VariableNames, 'feat_')};
            [~, score] = pca(featData); pc1 = score(:, 1);
            data_pca = cell(3, 1);
            for i=1:3, data_pca{i,1} = pc1(tsneData.label == (i-1)); end
            figPCA = figure('Name', 'PCA Raincloud', 'Color', 'w', 'Position', [100, 100, 800, 600]);
            h_pca = rm_raincloud(data_pca, [0.5 0.5 0.5], 1, 'ks');
            for i = 1:3
                h_pca.p{i, 1}.FaceColor = colors(i, :); h_pca.p{i, 1}.FaceVertexCData = colors(i, :);
                h_pca.s{i, 1}.MarkerFaceColor = colors(i, :); h_pca.s{i, 1}.MarkerEdgeColor = 'none';
                h_pca.m(i, 1).MarkerFaceColor = colors(i, :);
            end
            title('Feature Distribution on PC1 (Early Concat)');
            xlabel('Principal Component 1 (PC1)'); ylabel('Condition');
            set(gca, 'YTick', 1:3); set(gca, 'YTickLabel', {'Single', 'Competition', 'Cooperation'});
            grid on; saveas(figPCA, fullfile(outputFigDir, 'fig_pca_raincloud_early_concat.png'));
        end
    end
    
else
    fprintf('Warning: Gaze data file not found.\n');
end

% =========================================================================
% Part 2: EEG Entropy Analysis
% =========================================================================
eegFile = fullfile(dataDir, 'eeg_entropy_raw.csv');
if exist(eegFile, 'file')
    fprintf('\nLoading EEG data...\n');
    eegData = readtable(eegFile); eegData.condition = categorical(eegData.condition, conditions);
    eegStats = grpstats(eegData, 'condition', {'mean', 'std'}, 'DataVars', 'mean_entropy');
    disp(eegStats);
    figure('Name', 'EEG Raincloud', 'Color', 'w', 'Position', [100, 100, 800, 600]);
    data_eeg = cell(3, 1);
    for i=1:3, data_eeg{i,1} = eegData.mean_entropy(eegData.condition == conditions{i}); end
    rm_raincloud(data_eeg, [0.4, 0.5, 0.7], 0, 'ks');
    title('EEG Spectral Entropy Distribution'); xlabel('Mean Spectral Entropy (bits)');
    set(gca, 'YTickLabel', {'Single', 'Competition', 'Cooperation'}); grid on;
    saveas(gcf, fullfile(outputFigDir, 'fig_eeg_raincloud.png'));
    
    channelData = eegData{:, channelNames}; heatmapData = zeros(3, 32);
    for i = 1:3, idx = eegData.condition == conditions{i}; if any(idx), heatmapData(i, :) = mean(channelData(idx, :), 1); end; end
    figure('Name', 'EEG Heatmap', 'Color', 'w', 'Position', [100, 100, 1000, 400]);
    h = heatmap(channelNames, conditions, heatmapData);
    h.Title = 'Mean Spectral Entropy per Channel'; saveas(gcf, fullfile(outputFigDir, 'fig_eeg_channel_heatmap.png'));
end

% =========================================================================
% Part 3: Cross-Modality Correlation
% =========================================================================
if exist('gazeData','var') && exist('eegData','var')
    mergedData = innerjoin(gazeData, eegData, 'Keys', {'pair_id', 'player', 'trial_idx', 'condition'});
    if ~isempty(mergedData)
        figure('Name', 'Correlation', 'Color', 'w', 'Position', [100, 100, 800, 600]); hold on;
        for i = 1:3, idx = mergedData.condition == conditions{i}; if any(idx), scatter(mergedData.spatial_entropy(idx), mergedData.mean_entropy(idx), 50, 'Filled', 'MarkerFaceColor', colors(i,:), 'DisplayName', conditions{i}); end; end
        [R, P] = corrcoef(mergedData.spatial_entropy, mergedData.mean_entropy);
        title(sprintf('Gaze vs EEG Entropy (R = %.3f, p = %.3f)', R(1,2), P(1,2)));
        xlabel('Gaze Entropy'); ylabel('EEG Entropy'); legend('Location', 'best'); grid on;
        saveas(gcf, fullfile(outputFigDir, 'fig_correlation.png'));
    end
end

fprintf('\nAnalysis Complete!\n');